### ISSUE TITLE
Close body element

### ISSUE THREAD

**Issue by maiki** [jamestomasino/blog.tomasino.org#1]
Aside from your 404, your templates are not including a closing `body` element tag. I imagine it is because one would normally include a footer, but your minimalist style doesn't require anything there, so it was left out.

I suggest adding your contact info to a small footer partial, via an [`address`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address) element! :smile:

**Comment by jamestomasino** [comment]
OHNOES!

**Comment by jamestomasino** [comment]
Added closing body and html tags to index and list & single defaults.
